# Generated by Django 5.1.6 on 2025-03-04 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
        ('students', '0002_alter_student_parent_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
            preserve_default=False,
        ),
    ]
