# Generated by Django 5.1.6 on 2025-03-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_student'),
        ('students', '0002_alter_student_parent_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='month',
            field=models.CharField(default='2025-01', max_length=7),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('student', 'month')},
        ),
    ]
