# Generated by Django 5.1.6 on 2025-03-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_invoice_month_alter_invoice_unique_together'),
        ('students', '0002_alter_student_parent_email_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='invoice',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], default='draft', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('student', 'month', 'status')},
        ),
    ]
