# Generated by Django 5.1.6 on 2025-03-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='custom_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Leave blank to use student's default rate", max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='Duration in hours (e.g., 0.5 for 30 minutes, 1.0 for 1 hour)', max_digits=3),
        ),
    ]
